---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: eudaimonia
# description will be included in the image's metadata
description: A lightweight and minimal custom bluebuild image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files

  - type: brew
    brew-analytics: false
      
  - type: dnf
    repos:
     	nonfree: rpmfusion
     	cleaunp: true
   install: 
      packages:
        -afetch
        -onefetch
        -rofi
        -sakura
    group-install:
    with-optional: true
      packages: 
        - @basic-desktop
    group-remove:
      packages:
        - @gnome-desktop
  
  - type: fonts
      fonts:
        nerd-fonts: 
          - Hack
          - NerdFontsSymbolsOnly
          
  - type: os-release
      properties:
        ID: blue_build
        ID_LIKE: fedora
        NAME: Eudaimonia
        PRETTY_NAME: Eudaimonia 
        
  - type: signing
  
  
        
        
